songifi/lyricsflip_server

.env.example, .gitignore, .prettierrc, eslint.config.mjs, nest-cli.json, package-lock.json, package.json, src/app.controller.spec.ts, src/app.controller.ts, src/app.module.ts, src/app.service.ts, src/config/env.validation.ts, src/main.ts, test/app.e2e-spec.ts, test/jest-e2e.json, tsconfig.build.json, tsconfig.json
=> Feat: Initialiaze NestJs Project

.env.example, package-lock.json, package.json, src/app.controller.ts, src/app.module.ts, src/app.service.ts, src/main.ts
=> MongoDB setup and configuration

.github/workflows/ci.yml, .github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml, src/app.module.ts, src/app.service.ts
=> Configure CI/CD Pipeline with GitHub Actions

package-lock.json, package.json, src/app.module.ts, src/dto/lyrics.dto.ts, src/dto/users.dto.ts, src/lyrics/lyrics.controller.ts, src/lyrics/lyrics.module.ts, src/schemas/user.schema.ts, src/user/user.controller.ts, src/user/user.module.ts, src/user/user.service.ts
=> feat: :sparkles: Add user module

src/dto/create-follow.dto.ts, src/dto/follow-query.dto.ts, src/dto/update-follow-status.dto.ts, src/follow/follow.controller.ts, src/follow/follow.module.ts, src/follow/follow.service.ts, src/follow/tests/follow.service.spec.ts, src/schemas/follow.schema.ts
=> feat: Create Follow Resource Module and Schema

src/user/user.controller.ts, src/user/user.module.ts, src/user/user.service.ts
user registration endpoints implemented
=> implemented user registation endpoints

src/Block/block-controller.ts, src/Block/block-dto.ts, src/Block/block-module.ts, src/Block/block-schema.ts, src/Block/block-service.ts, src/Block/block-tests.ts
=> Create Block resource module and schema

src/app.module.ts, src/comments/comments.controller.spec.ts, src/comments/comments.controller.ts, src/comments/comments.module.ts, src/comments/comments.service.spec.ts, src/comments/comments.service.ts, src/dto/create-comment.dto.ts, src/dto/pagination-query-dto.ts, src/dto/update-comment.dto.ts, src/schemas/comment.schema.ts
=> Create comment resource module and schema #40

src/app.module.ts, src/category/category.controller.ts, src/category/category.module.ts, src/category/category.service.ts, src/category/dtos/create-category.dto.ts, src/category/dtos/update-category.dto.ts, src/dto/lyric.dto.ts, src/lyrics/lyric.controller.ts, src/lyrics/lyric.module.ts, src/lyrics/lyric.service.ts, src/schemas/category.schema.ts, src/schemas/lyric.schema.ts
the category resource was created and all required validation was done in the schema with relationship..
=> Category-resource successfully created

src/activity-feed/activity-controller.ts, src/activity-feed/activity-dtos.ts, src/activity-feed/activity-module.ts, src/activity-feed/activity-schema.ts, src/activity-feed/activity-service.ts
=> feat: Implement Activity feed service

src/modules/discovery/controllers/content-discovery.controller.ts, src/modules/discovery/discovery.module.ts, src/modules/discovery/services/ab-testing.service.ts, src/modules/discovery/services/content-discovery.service.ts, src/modules/discovery/services/recommendation-cache.service.ts, src/modules/discovery/services/scoring.service.ts, src/modules/discovery/test/content-discovery.service.spec.ts, src/modules/discovery/test/discovery.controller.spec.ts
**Description**
close #51
This PR introduces the Content Discovery Service, leveraging social signals to enhance content recommendations, trending content identification, and user discovery.
Acceptance Criteria
✅ Implemented ContentDiscoveryService using social interactions
✅ Developed personalized content recommendations
✅ Built trending content identification logic
✅ Added "People you may know" suggestions
✅ Created content popularity scoring
✅ Implemented discovery feeds showcasing popular content in users' networks
✅ Enhanced social-based search ranking
**Technical Implementation**
-     Developed a service layer to process content discovery
-     Implemented recommendation algorithms based on social interactions
-     Added trending detection algorithms to highlight popular content
- …
=> Add discovery module with content recommendations and caching services

src/privacy/privacy-controller.ts, src/privacy/privacy-decorators (1).ts, src/privacy/privacy-decorators.ts, src/privacy/privacy-dtos.ts, src/privacy/privacy-entity.ts, src/privacy/privacy-guard.ts, src/privacy/privacy-module.ts, src/privacy/privacy-service (1).ts, src/privacy/privacy-service-test.ts, src/privacy/privacy-service.ts
=> Build Privacy section

src/activity/activity.module.ts, src/activity/controllers/activity.controller.ts, src/activity/denormalization.md, src/activity/dto/activity-response.dto.ts, src/activity/dto/create-activity.dto.ts, src/activity/dto/query-activity.dto.ts, src/activity/schemas/activity.schema.ts, src/activity/services/activity.service.ts, src/activity/test/activity.controller.spec.ts, src/activity/test/activity.e2e-spec.ts, src/activity/test/activity.service.spec.ts
=> activity resource module

src/game-round/game-round-controller.ts, src/game-round/game-round-dtos.ts, src/game-round/game-round-entity.ts, src/game-round/game-round-event-listeners.ts, src/game-round/game-round-events.ts, src/game-round/game-round-module.ts, src/game-round/game-round-repository.ts, src/game-round/game-round-service.ts
=> game round resource added

src/round-answer/round-answer-dtos.ts, src/round-answer/round-answer-entity.ts, src/round-answer/round-answer-events.ts, src/round-answer/round-answer-listeners.ts, src/round-answer/round-answer-repository.ts, src/round-answer/round-answer/answer-validation-service.ts, src/round-answer/round-answer/round-answer-controller.ts, src/round-answer/round-answer/round-answer-dtos.ts, src/round-answer/round-answer/round-answer-entity.ts, src/round-answer/round-answer/round-answer-events.ts, src/round-answer/round-answer/round-answer-listeners.ts, src/round-answer/round-answer/round-answer-module.ts, src/round-answer/round-answer/round-answer-repository.ts, src/round-answer/round-answer/round-answer-service.ts
=> round-answres

src/follow/follow-cache-service.ts, src/follow/follow-controller.ts, src/follow/follow-dtos.ts, src/follow/follow-entity.ts, src/follow/follow-event-listeners.ts, src/follow/follow-events.ts, src/follow/follow-module.ts, src/follow/follow-repositories.ts, src/follow/follow-request-entity.ts, src/follow/follow-request-repository.ts, src/follow/follow-service.ts, src/follow/rate-limiter-service.ts
=> full follow resours added

src/notifications/notification-controller.ts, src/notifications/notification-dtos.ts, src/notifications/notification-factory-service.ts, src/notifications/notification-gateway.ts, src/notifications/notification-integration-service.ts, src/notifications/notification-module.ts, src/notifications/notification-schema.ts, src/notifications/notification-service.ts
this PR introduces the Implementation of  a NestJS Notification module with MongoDB schema to manage user notifications, supporting various types (follow, like, comment, share), status tracking, validation, indexing, and TTL for expiration.
=> Created Notification resource module and schema

src/block/block-controller.ts, src/block/block-dtos.ts, src/block/block-entity.ts, src/block/block-event-listeners.ts, src/block/block-events.ts, src/block/block-guard.ts, src/block/block-middleware.ts, src/block/block-module.ts, src/block/block-repository.ts, src/block/block-service.ts, src/block/content-filter-service.ts
This PR successfully implements the user blocking functionality with a well-structured service layer. Here’s a breakdown of what was accomplished:  
Key Implementations:
- BlockService with full business logic – Handles blocking, unblocking, and managing blocked users.  
- User Blocking & Unblocking – Users can now block and unblock others, with proper state management.  
- Blocked Users Listing – Implemented an efficient way to retrieve blocked users.  
- Content Visibility Filtering– Ensured that blocked users' content is hidden from searches, recommendations, and feeds.  
- Interaction Prevention – Blocked users cannot interact with each other (e.g., messages, comments, likes).  
- Performance Optimization – Optimized block checks to reduce query load.  
- Event Emission for Block …
=> feat: Implement Block service and visibility rules

src/not-delivery/notification-batch-entity.ts, src/not-delivery/notification-batch-repository.ts, src/not-delivery/notification-delivery-service.ts, src/not-delivery/notification-dtos.ts, src/not-delivery/notification-entity.ts, src/not-delivery/notification-gateway.ts, src/not-delivery/notification-preference-entity.ts, src/not-delivery/notification-preference-repository.ts, src/not-delivery/notification-repository.ts, src/not-delivery/notification-service.ts, src/not-delivery/notification-template-entity.ts, src/not-delivery/notification-template-repository.ts, src/not-delivery/notification-template-service (1).ts, src/not-delivery/notification-template-service.ts
This PR introduces a comprehensive user notification system, ensuring real-time and efficient delivery of notifications. Here’s what was accomplished:  
Key Implementations:
- NotificationService with full business logic – Manages notification creation, delivery, and retrieval.  
- Notification Generation – Implemented notifications for various social activities (e.g., likes, comments, follows).  
- WebSocket Integration – Enabled real-time notification delivery via WebSockets.  
- Read/Unread Management – Users can now mark notifications as read or unread.  
- Filtering & Retrieval– Added filtering options for retrieving notifications based on status and type.  
- Notification Preferences – Users can customize which notifications they receive.  
- Batching & Throttling – Optimized …
=> feat: Implement Notification service and delivery system

src/Like/like-service.ts
=> Like service properly implemented

src/gam-rounds/game-round-controller.ts, src/gam-rounds/game-round-dtos.ts, src/gam-rounds/game-round-module.ts, src/gam-rounds/game-round-schema.ts, src/gam-rounds/game-round-service.ts
=> added game_rounds folder

src/comment/comment-controller.ts, src/comment/comment-dtos.ts, src/comment/comment-entities.ts, src/comment/comment-module.ts, src/comment/comment-service.ts
=> feat: implement comment

src/share/share-controller.ts, src/share/share-dtos.ts, src/share/share-entities.ts, src/share/share-service.ts
- Develop `ShareService` with full business logic
- Add internal sharing functionality
- Implement external platform sharing (link/embed generation)
- Integrate share tracking and analytics
- Build shared content retrieval with filtering
- Implement share notifications and activity feed
- Ensure platform-specific share formatting
- Enable content preview generation
- Apply rate limiting for share operations
- Emit events for share lifecycle tracking
Closes: [issue/ticket number if applicable]
=> feat: Implement content sharing service and operations

src/sm-likes/like-controller.ts, src/sm-likes/like-dtos.ts, src/sm-likes/like-entity.ts, src/sm-likes/like-migration.ts, src/sm-likes/like-repository.ts
closes #91
Implement Like entity structure for social media functionality
This PR introduces the foundational structure for the Like entity in our music application, enabling users to like songs, playlists, albums, artists, and user-generated content.
Key Implementations:
✅ Entity & Database:
Defined Like entity using TypeORM with polymorphic relationships.
Added composite unique constraints to prevent duplicate likes.
Created migration scripts for database setup.
Implemented indexing for optimized queries.
✅ DTOs & Validation:
Created CreateLikeDto, LikeResponseDto, LikeFilterDto, and LikeStatsDto.
Added input validation and Swagger documentation.
✅ Controller & API Endpoints:
Implemented endpoints for liking, unliking, checking like status, and retrieving likes.
Applied authentication …
=> feat: Implement Like entity structure and API endpoints

src/app.module.ts, src/likes/dto/create-like.dto.ts, src/likes/likes.controller.ts, src/likes/likes.module.ts, src/likes/likes.service.ts
- Implemented Like module in NestJS.
- Created LikeSchema with validation and indexing.
- Added support for polymorphic relationships (songs, playlists, users).
- Optimized query performance using compound indexing.
- Followed NestJS module architecture best practices.
closes #36
=> feat: Implement Like module with Mongoose schema and polymorphic relationships
